### ISSUE TITLE
ripme.xyz website gone

### ISSUE THREAD

**Issue by ZandercraftGames** [deansheather/ripme.xyz#15]
The ripme.xyz website no longer exists....
![screen shot 2018-09-07 at 2 45 41 pm](https://user-images.githubusercontent.com/28664144/45237445-b7a59000-b2ac-11e8-9d28-da057fe6931f.png)

**Comment by deansheather** [comment]
I stopped paying for it since it was a dead meme. Someone else parked it, which is why you see that stuff displayed on it.

**Comment by ZandercraftGames** [comment]
Oh... RIP
