### ISSUE TITLE
v2 Planned features

### ISSUE THREAD

**Issue by deansheather** [deansheather/ripme.xyz#4]
- [x] Quotes
- [x] Some hidden eastereggs

Ideas are welcome. Post comments.

**Comment by SteamingMutt** [comment]
comments.

**Comment by DoNotSpamPls** [comment]
add b1nzy's face somewhere in 👀

**Comment by jayktaylor** [comment]
hot

**Comment by FishyFing** [comment]
discord fm v2

**Comment by Technochips** [comment]
there's should be "no big soup rice" as a quote, cuz y not

**Comment by deansheather** [comment]
Quotes can be added here, @Julien12150: https://docs.google.com/forms/d/e/1FAIpQLScHRLE6dxOwelWbA7OzNRZ79xstJU6ZRLkpFrXUdp1TdSBR6w/viewform

**Comment by deansheather** [comment]
This is out, didn't bother with video backgrounds because no one cares.

Also the site is static now. Yay!
